compressionLevel: mixed

enableGlobalCache: false

nmMode: hardlinks-local

nodeLinker: node-modules

npmPublishAccess: public

npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
